---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.namespace }}
spec:
  id: ${{ values.name }}
  compositionSelector:
    matchLabels:
      provider: ${{ values.provider }}
  parameters:
    version: ${{ values.version }}
    nodeSize: ${{ values.nodeSize }}
    minNodeCount: ${{ values.minNodeCount }}
    namespaces: [${{ values.namespaces }}]
    apps:
      crossplane:
        enabled: ${{ values.crossplane.enabled }}
      argocd:
        enabled: ${{ values.argocd.enabled }}
        host: ${{ values.argocd.host }}
        repoURL: ${{ values.argocd.repoURL }}
        destinationNamespace: ${{ values.argocd.destinationNamespace }}
        sourcePath: ${{ values.argocd.sourcePath }}
      openfunction:
        enabled: ${{ values.openfunction.enabled }}
      dapr:
        enabled: ${{ values.dapr.enabled }}
      traefik:
        enabled: ${{ values.traefik.enabled }}
