providers:
  google_secrets_manager:
    kind: google_secretmanager
    maps:
      - id: secrets
        path: projects/vfarcic
        keys:
          upbound-account: UP_ACCOUNT
          upbound-token: UP_TOKEN
          github-token: GITHUB_TOKEN
          github-user: GITHUB_OWNER
