apiVersion: devopstoolkitseries.com/v1alpha1
kind: App
metadata:
  name: silly-demo
  labels:
    app-owner: vfarcic
spec:
  id: silly-demo
  compositionRef:
    name: app-backend
  parameters:
    namespace: production
    image: vfarcic/silly-demo:1.0.2
    port: 8080
