apiVersion: devopstoolkit.live/v1beta1
kind: App
metadata:
  name: silly-demo
spec:
  crossplane:
    compositionSelector:
      matchLabels:
        type: backend
  image: ghcr.io/vfarcic/silly-demo
  tag: v1.5.235
  port: 8080
  host: silly-demo.54.159.100.244.nip.io
  routing: gateway-api
  providerConfigName: a-team
  targetNamespace: dev
  minReplicas: 0
  maxReplicas: 5
  scaling:
    enabled: true
    prometheusAddress: http://kube-prometheus-stack-prometheus.prometheus-system:9090
