---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  name: silly-demo-app
spec:
  id: silly-demo-app
  compositionSelector:
    matchLabels:
      type: backend-db
      location: remote
  parameters:
    namespace: production
    image: vfarcic/sql-demo:0.1.10
    port: 8080
    host: devops-toolkit.127.0.0.1.nip.io
    kubernetesProviderConfigName: a-team-eks
    dbSecret:
      name: silly-demo-db-aws
      namespace: a-team

---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: silly-demo-db
spec:
  id: silly-demo-db
  compositionSelector:
    matchLabels:
      provider: aws
      db: postgresql
  parameters:
    version: "13.4"
    size: small
    namespace: production
  writeConnectionSecretToRef:
    name: silly-demo-db-aws
