apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  name: silly-demo
  labels:
    app-owner: vfarcic
spec:
  id: silly-demo
  compositionSelector:
    matchLabels:
      type: backend
      location: local
  parameters:
    namespace: production
    image: vfarcic/silly-demo:1.0.8
    port: 8080
    host: silly-demo.34.148.247.11.nip.io
