apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  name: silly-demo
spec:
  id: silly-demo
  compositionSelector:
    matchLabels:
      type: backend-db-google
      location: local
  parameters:
    namespace: a-team
    image: c8n.io/vfarcic/silly-demo:1.4.52
    port: 8080
    host: silly-demo.127.0.0.1.nip.io
    db:
      version: "14"
      size: small
