apiVersion: devopstoolkit.live/v1beta1
kind: App
metadata:
  name: silly-demo
spec:
  image: ghcr.io/vfarcic/silly-demo
  tag: v1.5.46
  port: 8080
  host: silly-demo.127.0.0.1.nip.io
  ingressClassName: nginx
  scaling:
    enabled: true
    min: 2
    max: 5
  crossplane:
    compositionSelector:
      matchLabels:
        type: backend
        location: local
---
apiVersion: devopstoolkit.live/v1beta1
kind: App
metadata:
  name: silly-demo-frontend
spec:
  image: ghcr.io/vfarcic/silly-demo-frontend
  tag: v1.5.46
  port: 3000
  host: silly-demo-frontend.127.0.0.1.nip.io
  ingressClassName: nginx
  frontend:
    backendUrl: http://silly-demo.127.0.0.1.nip.io
  crossplane:
    compositionSelector:
      matchLabels:
        type: frontend
        location: local
