apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: dot-application
  annotations:
    meta.crossplane.io/maintainer: Viktor Farcic (@vfarcic)
    meta.crossplane.io/source: github.com/vfarcic/crossplane-app
    meta.crossplane.io/license: MIT
    meta.crossplane.io/description: Application types (frontend, backend, and backend with a database)
    meta.crossplane.io/readme: A Configuration package that defines application types like frontend, backend, and backend with a database.
spec:
  dependsOn:
    - provider: xpkg.crossplane.io/crossplane-contrib/provider-kubernetes
      version: ">=v1.2.0"
    - function: xpkg.crossplane.io/crossplane-contrib/function-kcl
      version: ">=v0.10.0"
    - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
      version: ">=v0.2.0"
