name: Build
on:
  push:
    branches:
      - main
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install the `up` CLI
        run: |
          curl -sLo up.deb "https://cli.upbound.io/stable/${VERSION}/deb/linux_${ARCH}/up.deb"
          ./up login
      - name: Build the package
        run: |
          export VERSION=v0.5.${{ github.run_number }}
          ./up xpkg build --name app.xpkg
          ./up xpkg push --package app.xpkg xpkg.upbound.io/$UP_ACCOUNT/dot-application:$VERSION
