name: Build
on:
  push:
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install Devbox
        uses: jetpack-io/devbox-install-action@v0.12.0
        with:
          enable-cache: true
      - name: Test
        run: devbox run test
      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: |
          export UP_TOKEN=${{ secrets.UP_TOKEN }}
          export UP_ACCOUNT=${{ secrets.UP_ACCOUNT }}
          export VERSION=v0.8.${{ github.run_number }}
          devbox run package-publish
      - name: Commit changes
        if: github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Config update [skip ci]"
      - name: Push changes
        if: github.ref == 'refs/heads/main'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CROSSPLANE_TOKEN }}
          branch: ${{ github.ref }}
