name: Release
on:
  push:
    branches:
      - main
jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install Upbound CLI
        run: |
          curl -sL "https://cli.upbound.io" | sh
          sudo mv up /usr/local/bin/
      - name: Install Devbox
        uses: jetpack-io/devbox-install-action@v0.14.0
        with:
          enable-cache: true
      - name: Build the package
        run: |
          GOBIN=$RUNNER_TEMP go install github.com/maykonlsf/semver-cli/cmd/semver@latest
          export UP_TOKEN=${{ secrets.UP_TOKEN }}
          export UP_ACCOUNT=${{ secrets.UP_ACCOUNT }}
          export VERSION=$($RUNNER_TEMP/semver up release)
          devbox run package-publish
      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Config update [skip ci]"
      - name: Push changes
        uses: ad-m/github-push-action@v1.0.0
        with:
          github_token: ${{ secrets.CROSSPLANE_TOKEN }}
          branch: ${{ github.ref }}
